// <auto-generated />
using System;
using Dynamite.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dynamite.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dynamite.Core.Entities.AntiSpamConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AntiInvite")
                        .HasColumnType("boolean");

                    b.Property<bool>("AntiRaid")
                        .HasColumnType("boolean");

                    b.Property<bool>("AntiScamLink")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GuildConfigId")
                        .HasColumnType("uuid");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("MentionThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("MessageThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("MessageWindowSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("RaidThreshold")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId")
                        .IsUnique();

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("AntiSpamConfigs");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.AutoRoleConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GuildConfigId")
                        .HasColumnType("uuid");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId");

                    b.HasIndex("GuildId", "RoleId")
                        .IsUnique();

                    b.ToTable("AutoRoleConfigs");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.CaughtFish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BagId")
                        .HasColumnType("uuid");

                    b.Property<long>("CoinValue")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FishEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FishName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsPearl")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpecialCreature")
                        .HasColumnType("boolean");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourcePool")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("BagId");

                    b.HasIndex("GuildId", "UserId");

                    b.ToTable("CaughtFish", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.FishingActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CoinsEarned")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FishName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("PondRemaining")
                        .HasColumnType("integer");

                    b.Property<string>("PoolName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rarity")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RodName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Weather")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GuildId", "CreatedAt");

                    b.HasIndex("GuildId", "UserId", "CreatedAt");

                    b.ToTable("FishingActivityLogs", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.FishingDataSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AchievementIds")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("BagCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("BagSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChestsOpened")
                        .HasColumnType("integer");

                    b.Property<int>("CommonCaught")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FishingLevel")
                        .HasColumnType("integer");

                    b.Property<long>("FishingXp")
                        .HasColumnType("bigint");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("LegendaryCaught")
                        .HasColumnType("integer");

                    b.Property<int>("MythicCaught")
                        .HasColumnType("integer");

                    b.Property<int>("RareCaught")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TotalCaught")
                        .HasColumnType("integer");

                    b.Property<int>("UncommonCaught")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("WalletCoins")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId", "CreatedAt");

                    b.ToTable("FishingDataSnapshots", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.Giveaway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClaimMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("HostId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnded")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("JoinedBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("MinJoinDays")
                        .HasColumnType("integer");

                    b.Property<long?>("PingRoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PreSelectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PreSelectedBy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("PreSelectedWinnerIds")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Prize")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WinnerCount")
                        .HasColumnType("integer");

                    b.Property<string>("WinnerIds")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("GuildId", "IsEnded");

                    b.ToTable("Giveaways", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.GiveawayEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GiveawayId")
                        .HasColumnType("uuid");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GiveawayId", "UserId")
                        .IsUnique();

                    b.ToTable("GiveawayEntries", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.GuildConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AuditLogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("AutoRoleEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DailyChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("FishingChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("FishingLeaderboardChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LoggingEnabled")
                        .HasColumnType("boolean");

                    b.Property<long?>("MemberLogChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MessageLogChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModLogChannelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ModerationEnabled")
                        .HasColumnType("boolean");

                    b.Property<long?>("ServerLogChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("VerifyChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VerifyRemoveRoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VerifyRoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VoiceLogChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WelcomeChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("WelcomeEmbedColor")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("WelcomeEmbedFooter")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("WelcomeEmbedTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("WelcomeEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("WelcomeImageEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("GuideChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("InvoiceChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ServerLeaderboardChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ShopChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ShopShowcaseMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("SpecialPoolChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("WeatherChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("WeatherForecastMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("WelcomeMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.GuildLevelRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("LevelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "LevelType", "RequiredLevel")
                        .IsUnique();

                    b.ToTable("GuildLevelRoles", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.GuildPearlLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("PearlType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "PearlType", "CreatedAt");

                    b.ToTable("GuildPearlLogs", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.GuildPond", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentFish")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentWeather")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DailyChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("DepletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FishingChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("MaxFish")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResetAvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WeatherExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("GuildPonds", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.GuildPresence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IconHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("GuildPresences");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CooldownSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double?>("DropMultiplier")
                        .HasColumnType("double precision");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<double?>("EscapeRate")
                        .HasColumnType("double precision");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<double?>("MissRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Name")
                        .IsUnique();

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.LeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeltaRank")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Rank");

                    b.ToTable("LeaderboardEntries", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.LeaderboardSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Type", "WeekStartDate");

                    b.ToTable("LeaderboardSnapshots", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.ModerationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GuildConfigId")
                        .HasColumnType("uuid");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("ModeratorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TargetUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId");

                    b.HasIndex("GuildId", "TargetUserId");

                    b.ToTable("ModerationActions");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.RolePanel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid>("GuildConfigId")
                        .HasColumnType("uuid");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxRoles")
                        .HasColumnType("integer");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("PanelType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId");

                    b.HasIndex("GuildId", "MessageId");

                    b.ToTable("RolePanels");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.RolePanelItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emoji")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RolePanelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RolePanelId", "RoleId")
                        .IsUnique();

                    b.ToTable("RolePanelItems");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.SpecialPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DropTable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<string>("PoolName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RemainingFish")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "StartsAt", "ExpiresAt");

                    b.ToTable("SpecialPools", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.TempVoiceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultUserLimit")
                        .HasColumnType("integer");

                    b.Property<Guid>("GuildConfigId")
                        .HasColumnType("uuid");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("TriggerChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId")
                        .IsUnique();

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("TempVoiceConfigs");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TicketConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Topic")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.HasIndex("TicketConfigId");

                    b.HasIndex("GuildId", "Number")
                        .IsUnique();

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.TicketConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("NextTicketNumber")
                        .HasColumnType("integer");

                    b.Property<long>("PanelChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("PanelMessageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StaffRoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("TicketConfigs", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FromWalletId")
                        .HasColumnType("uuid");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ToWalletId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FromWalletId");

                    b.HasIndex("ToWalletId");

                    b.HasIndex("GuildId", "CreatedAt");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.UserFishBag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BagCapacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("UserFishBags", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.UserFishTrophy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsPearl")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("boolean");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId");

                    b.HasIndex("GuildId", "UserId", "FishName")
                        .IsUnique();

                    b.ToTable("UserFishTrophies", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.UserFishingAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AchievementId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserFishingAchievements", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.UserFishingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AutoFishChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("AutoFishExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AutoFishPurchaseCount")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoFishPaused")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoFishSellAll")
                        .HasColumnType("boolean");

                    b.Property<int>("ChestsOpened")
                        .HasColumnType("integer");

                    b.Property<int>("CommonCaught")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FishingLevel")
                        .HasColumnType("integer");

                    b.Property<long>("FishingXp")
                        .HasColumnType("bigint");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("LastFishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LegendaryCaught")
                        .HasColumnType("integer");

                    b.Property<int>("MythicCaught")
                        .HasColumnType("integer");

                    b.Property<int>("RareCaught")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCaught")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TradeWeekResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TradesThisWeek")
                        .HasColumnType("integer");

                    b.Property<int>("UncommonCaught")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("UserFishingProfiles", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.UserInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("WalletId", "ItemId")
                        .IsUnique();

                    b.ToTable("UserInventories", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.UserServerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("LastMessageXpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServerLevel")
                        .HasColumnType("integer");

                    b.Property<long>("ServerXp")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalVoiceMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("VoiceJoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("UserServerProfiles", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.UserWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Coins")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyStreak")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastDaily")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Coins");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("UserWallets", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.Warning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GuildConfigId")
                        .HasColumnType("uuid");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("ModeratorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TargetUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId");

                    b.ToTable("Warnings");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.WeeklyActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("WeekResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeeklyFishCaught")
                        .HasColumnType("integer");

                    b.Property<int>("WeeklyMessages")
                        .HasColumnType("integer");

                    b.Property<int>("WeeklyVoiceMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("WeeklyActivities", (string)null);
                });

            modelBuilder.Entity("Dynamite.Core.Entities.AntiSpamConfig", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.GuildConfig", "GuildConfig")
                        .WithOne("AntiSpamConfig")
                        .HasForeignKey("Dynamite.Core.Entities.AntiSpamConfig", "GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.AutoRoleConfig", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.GuildConfig", "GuildConfig")
                        .WithMany("AutoRoles")
                        .HasForeignKey("GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.CaughtFish", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.UserFishBag", "Bag")
                        .WithMany("Fish")
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bag");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.GiveawayEntry", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.Giveaway", "Giveaway")
                        .WithMany("Entries")
                        .HasForeignKey("GiveawayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Giveaway");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.LeaderboardEntry", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.LeaderboardSnapshot", "Snapshot")
                        .WithMany("Entries")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.ModerationAction", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.GuildConfig", "GuildConfig")
                        .WithMany("ModerationActions")
                        .HasForeignKey("GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.RolePanel", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.GuildConfig", "GuildConfig")
                        .WithMany("RolePanels")
                        .HasForeignKey("GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.RolePanelItem", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.RolePanel", "RolePanel")
                        .WithMany("Items")
                        .HasForeignKey("RolePanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolePanel");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.TempVoiceConfig", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.GuildConfig", "GuildConfig")
                        .WithOne("TempVoiceConfig")
                        .HasForeignKey("Dynamite.Core.Entities.TempVoiceConfig", "GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.Ticket", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.TicketConfig", "TicketConfig")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketConfig");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.Transaction", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.UserWallet", "FromWallet")
                        .WithMany("SentTransactions")
                        .HasForeignKey("FromWalletId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dynamite.Core.Entities.UserWallet", "ToWallet")
                        .WithMany("ReceivedTransactions")
                        .HasForeignKey("ToWalletId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FromWallet");

                    b.Navigation("ToWallet");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.UserFishingAchievement", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.UserFishingProfile", "Profile")
                        .WithMany("Achievements")
                        .HasForeignKey("GuildId", "UserId")
                        .HasPrincipalKey("GuildId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.UserInventory", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.InventoryItem", "Item")
                        .WithMany("Owners")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dynamite.Core.Entities.UserWallet", "Wallet")
                        .WithMany("Inventory")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.Warning", b =>
                {
                    b.HasOne("Dynamite.Core.Entities.GuildConfig", "GuildConfig")
                        .WithMany("Warnings")
                        .HasForeignKey("GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.Giveaway", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.GuildConfig", b =>
                {
                    b.Navigation("AntiSpamConfig");

                    b.Navigation("AutoRoles");

                    b.Navigation("ModerationActions");

                    b.Navigation("RolePanels");

                    b.Navigation("TempVoiceConfig");

                    b.Navigation("Warnings");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.InventoryItem", b =>
                {
                    b.Navigation("Owners");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.LeaderboardSnapshot", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.RolePanel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.TicketConfig", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.UserFishBag", b =>
                {
                    b.Navigation("Fish");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.UserFishingProfile", b =>
                {
                    b.Navigation("Achievements");
                });

            modelBuilder.Entity("Dynamite.Core.Entities.UserWallet", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("ReceivedTransactions");

                    b.Navigation("SentTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
