<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Dynamite.Application\Dynamite.Application.csproj" />
    <ProjectReference Include="..\Dynamite.Infrastructure\Dynamite.Infrastructure.csproj" />
    <ProjectReference Include="..\Dynamite.Core\Dynamite.Core.csproj" />
    <ProjectReference Include="..\Dynamite.Shared\Dynamite.Shared.csproj" />
    <ProjectReference Include="..\Dynamite.Modules\Setup\Dynamite.Modules.Setup.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.3.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8c8e049e-d7a3-44c3-a746-f9525fccdb69</UserSecretsId>
  </PropertyGroup>
</Project>