name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore src/Dynamite.Bot/Dynamite.Bot.csproj

      - name: Build
        run: dotnet build src/Dynamite.Bot/Dynamite.Bot.csproj --no-restore --configuration Release

      - name: Test
        run: dotnet test src/Dynamite.Tests/Dynamite.Tests.csproj --configuration Release --verbosity normal
